services:
  db:
    image: postgres:16-alpine
    container_name: news_postgres
    restart: always
    environment:
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: news_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: